[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
byteorder = { version = "1", default-features = false }
bitvec = { version = "1", default-features = false }
bitfield = "0.14"
derive_more = "0.99"
